### ISSUE TITLE
Feature Parity w/ Electrum

### ISSUE THREAD

**Issue by kilpatty** [HandshakeAlliance/nomenclate#3]
This will be a meta issue for tracking all remaining features that need to be implemented in Nomenclate. These are the remaining features that need to be implemented:

Http:
- [x] Block -> header
- [x] Block -> headers
- [x] Estimate Fee
- [x] ~~Headers -> suscribe~~
- [x] Relay Fee
- [ ] Address -> get mempool
- [x] Address -> list unspent
- [x] ~~Address -> Subscribe~~
- [x] Address -> Utxos
- [x] Tx -> Broadcast
- [x] Tx -> Get
- [x] Tx -> Get Merkle
- [x] Tx -> ID from Pos
- [x] ~~Mempool -> Changes~~
- [ ] Mempool -> Fee Histogram
- [x] ~~Server -> Add Peer~~
- [x] Server -> Banner
- [x] ~~Server -> Donation_address~~
- [x] Server -> Features
- [x] Server -> Ping
- [x] Server -> Version
- [x] ~~Peers -> Subscribe~~

rpc:
- [ ] Block -> header
- [ ] Block -> headers
- [ ] Estimate Fee
- [ ] Headers -> suscribe
- [ ] Relay Fee
- [ ] Address -> get mempool
- [ ] Address -> list unspent
- [ ] Address -> Subscribe
- [ ] Address -> Utxos
- [ ] Tx -> Broadcast
- [ ] Tx -> Get
- [ ] Tx -> Get Merkle
- [ ] Tx -> ID from Pos
- [ ] Mempool -> Changes
- [ ] Mempool -> Fee Histogram
- [ ] Server -> Add Peer
- [ ] Server -> Banner
- [x] ~~Server -> Donation_address~~
- [ ] Server -> Features
- [ ] Server -> Ping
- [ ] Server -> Version
- [ ] Peers -> Subscribe

GRPC:
- [ ] Block -> header
- [ ] Block -> headers
- [ ] Estimate Fee
- [ ] Headers -> suscribe
- [ ] Relay Fee
- [ ] Address -> get mempool
- [ ] Address -> list unspent
- [ ] Address -> Subscribe
- [ ] Address -> Utxos
- [ ] Tx -> Broadcast
- [ ] Tx -> Get
- [ ] Tx -> Get Merkle
- [ ] Tx -> ID from Pos
- [ ] Mempool -> Changes
- [ ] Mempool -> Fee Histogram
- [ ] Server -> Add Peer
- [ ] Server -> Banner
- [x] ~~Server -> Donation_address~~
- [ ] Server -> Features
- [ ] Server -> Ping
- [ ] Server -> Version
- [ ] Peers -> Subscribe

**Comment by kilpatty** [comment]
Quick thought -> Although I don't personally need any donations, we could entertain the thought of putting an official HNS address for the Alliance.
